# -*- coding: utf-8 -*-
"""UniPulse v3 高考选校数据 - 80所中国高校真实数据"""
# 数据来源: 软科2025中国大学排名 + 教育部数据 + 各校就业质量报告

UNIVERSITIES = [
    # TOP10 顶尖名校
    {"id":1,"name":"Tsinghua University","cn":"清华大学","loc":"北京","region":"华北","country":"中国","logo":"#c73e3a","initials":"TH","score":1076.1,"trend":"up","trendV":"+12.3","stars":4.9,"reviews":4820,"rank":1,"level":"985/211/双一流","type":"综合","metrics":{"学术":96.5,"科研":98.2,"就业":97.8,"国际化":85.3,"校园":92.1,"雇主声誉":96.4},"tags":[{"text":"985/211","type":"gold"},{"text":"顶尖名校","type":"red"},{"text":"理工见长","type":"blue"}],"description":"清华大学，中国最顶尖的高等学府，工科实力全球领先，QS世界排名前20。","gaokao_score":698,"tuition":5000,"employment_rate":98.2,"avg_salary":21900},
    {"id":2,"name":"Peking University","cn":"北京大学","loc":"北京","region":"华北","country":"中国","logo":"#00487c","initials":"PK","score":1027.7,"trend":"up","trendV":"+8.7","stars":4.9,"reviews":4610,"rank":2,"level":"985/211/双一流","type":"综合","metrics":{"学术":95.8,"科研":96.5,"就业":97.2,"国际化":92.1,"校园":94.8,"雇主声誉":98.1},"tags":[{"text":"985/211","type":"gold"},{"text":"顶尖名校","type":"red"},{"text":"文理并重","type":"purple"}],"description":"北京大学，中国最负盛名的综合性大学，文理基础学科蜚声国际，QS世界排名前30。","gaokao_score":696,"tuition":5000,"employment_rate":97.8,"avg_salary":21300},
    {"id":3,"name":"Zhejiang University","cn":"浙江大学","loc":"浙江","region":"华东","country":"中国","logo":"#00529b","initials":"ZJ","score":868.9,"trend":"up","trendV":"+5.2","stars":4.8,"reviews":3890,"rank":3,"level":"985/211/双一流","type":"综合","metrics":{"学术":88.4,"科研":92.1,"就业":93.5,"国际化":80.2,"校园":91.3,"雇主声誉":89.7},"tags":[{"text":"985/211","type":"gold"},{"text":"工科强校","type":"blue"},{"text":"浙江第一","type":"green"}],"description":"浙江大学，浙江省最强高校，学科门类最齐全的综合型大学，工科、医科、管理学均属顶尖。","gaokao_score":683,"tuition":5000,"employment_rate":96.5,"avg_salary":18200},
    {"id":4,"name":"Shanghai Jiao Tong University","cn":"上海交通大学","loc":"上海","region":"华东","country":"中国","logo":"#c40009","initials":"SJ","score":851.7,"trend":"up","trendV":"+6.1","stars":4.8,"reviews":3750,"rank":4,"level":"985/211/双一流","type":"综合","metrics":{"学术":89.2,"科研":91.5,"就业":95.8,"国际化":88.4,"校园":89.7,"雇主声誉":93.2},"tags":[{"text":"985/211","type":"gold"},{"text":"工科顶尖","type":"blue"},{"text":"上海第一","type":"red"}],"description":"上海交通大学，中国工科三强之一，船舶、机械、商科闻名，就业率长期稳居全国前三。","gaokao_score":685,"tuition":5000,"employment_rate":97.1,"avg_salary":19500},
    {"id":5,"name":"Fudan University","cn":"复旦大学","loc":"上海","region":"华东","country":"中国","logo":"#a50012","initials":"FD","score":788.4,"trend":"up","trendV":"+4.8","stars":4.8,"reviews":3620,"rank":5,"level":"985/211/双一流","type":"综合","metrics":{"学术":90.1,"科研":88.7,"就业":94.3,"国际化":91.5,"校园":93.2,"雇主声誉":95.8},"tags":[{"text":"985/211","type":"gold"},{"text":"文理强校","type":"purple"},{"text":"上海第二","type":"orange"}],"description":"复旦大学，上海最负盛名的综合性大学，新闻传播、经济学、数学、医学均属全国顶尖。","gaokao_score":680,"tuition":5000,"employment_rate":96.8,"avg_salary":18800},
    {"id":6,"name":"Nanjing University","cn":"南京大学","loc":"江苏","region":"华东","country":"中国","logo":"#003088","initials":"NJ","score":707.8,"trend":"up","trendV":"+3.5","stars":4.7,"reviews":3280,"rank":6,"level":"985/211/双一流","type":"综合","metrics":{"学术":91.3,"科研":87.2,"就业":91.8,"国际化":82.7,"校园":90.5,"雇主声誉":90.4},"tags":[{"text":"985/211","type":"gold"},{"text":"基础学科强","type":"purple"},{"text":"南京第一","type":"green"}],"description":"南京大学，前身中央大学，物理、天文、中文、历史等基础学科蜚声海内外，小规模精英教育著称。","gaokao_score":672,"tuition":5000,"employment_rate":95.2,"avg_salary":16800},
    {"id":7,"name":"University of Science and Technology of China","cn":"中国科学技术大学","loc":"安徽","region":"华东","country":"中国","logo":"#c40009","initials":"UC","score":637.0,"trend":"up","trendV":"+2.9","stars":4.7,"reviews":2890,"rank":7,"level":"985/211/双一流","type":"理工","metrics":{"学术":93.8,"科研":95.2,"就业":90.5,"国际化":78.3,"校园":85.7,"雇主声誉":88.9},"tags":[{"text":"985/211","type":"gold"},{"text":"科研见长","type":"blue"},{"text":"小而精","type":"cyan"}],"description":"中国科学技术大学，理工科研究型大学，物理、化学、计算机、人工智能居全国顶尖，留学率极高。","gaokao_score":674,"tuition":5000,"employment_rate":95.8,"avg_salary":19200},
    {"id":8,"name":"Wuhan University","cn":"武汉大学","loc":"湖北","region":"华中","country":"中国","logo":"#c40009","initials":"WH","score":629.2,"trend":"up","trendV":"+4.1","stars":4.6,"reviews":4120,"rank":8,"level":"985/211/双一流","type":"综合","metrics":{"学术":83.2,"科研":85.7,"就业":89.3,"国际化":75.8,"校园":95.8,"雇主声誉":85.4},"tags":[{"text":"985/211","type":"gold"},{"text":"樱花名校","type":"pink"},{"text":"武汉第一","type":"orange"}],"description":"武汉大学，中国最美大学之一，法学、水利、图书情报与档案管理居全国顶尖，校园风景闻名全国。","gaokao_score":662,"tuition":5000,"employment_rate":94.5,"avg_salary":15200},
    {"id":9,"name":"Huazhong University of Science and Technology","cn":"华中科技大学","loc":"湖北","region":"华中","country":"中国","logo":"#003087","initials":"HZ","score":628.9,"trend":"up","trendV":"+5.7","stars":4.6,"reviews":3580,"rank":9,"level":"985/211/双一流","type":"理工","metrics":{"学术":82.5,"科研":87.8,"就业":91.2,"国际化":72.4,"校园":86.3,"雇主声誉":87.6},"tags":[{"text":"985/211","type":"gold"},{"text":"工科强校","type":"blue"},{"text":"武汉第二","type":"cyan"}],"description":"华中科技大学，机械工程、光电工程、公共卫生居全国领先，与武汉大学同城双星，就业质量高。","gaokao_score":660,"tuition":5000,"employment_rate":95.1,"avg_salary":15800},
    {"id":10,"name":"Xi'an Jiaotong University","cn":"西安交通大学","loc":"陕西","region":"西北","country":"中国","logo":"#c40009","initials":"XA","score":598.5,"trend":"up","trendV":"+3.2","stars":4.6,"reviews":3010,"rank":10,"level":"985/211/双一流","type":"综合","metrics":{"学术":84.1,"科研":86.3,"就业":90.8,"国际化":71.5,"校园":83.9,"雇主声誉":86.2},"tags":[{"text":"985/211","type":"gold"},{"text":"管理工程强","type":"blue"},{"text":"西安第一","type":"red"}],"description":"西安交通大学，中国电气工程、管理科学与工程顶尖高校，钱学森创办，工程师摇篮，西北最强。","gaokao_score":658,"tuition":5000,"employment_rate":94.8,"avg_salary":15500},

    # 11-30 知名985
    {"id":11,"name":"Beihang University","cn":"北京航空航天大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"BH","score":585.4,"trend":"up","trendV":"+4.0","stars":4.6,"reviews":2680,"rank":11,"level":"985/211/双一流","type":"理工","metrics":{"学术":87.3,"科研":91.5,"就业":94.2,"国际化":74.1,"校园":82.8,"雇主声誉":90.5},"tags":[{"text":"985/211","type":"gold"},{"text":"航空航天","type":"blue"},{"text":"工科强校","type":"cyan"}],"description":"北京航空航天大学，中国航空航天领域最高学府，航空宇航科学与技术全国第一，工信部直属。","gaokao_score":660,"tuition":5000,"employment_rate":96.2,"avg_salary":18500},
    {"id":12,"name":"Sun Yat-sen University","cn":"中山大学","loc":"广东","region":"华南","country":"中国","logo":"#c40009","initials":"SY","score":585.2,"trend":"up","trendV":"+2.8","stars":4.5,"reviews":3980,"rank":12,"level":"985/211/双一流","type":"综合","metrics":{"学术":82.1,"科研":83.4,"就业":88.7,"国际化":82.3,"校园":90.1,"雇主声誉":84.7},"tags":[{"text":"985/211","type":"gold"},{"text":"医科顶尖","type":"red"},{"text":"广州第一","type":"green"}],"description":"中山大学，华南第一高校，医学、管理学、公共卫生居全国领先，校区分布在广州、深圳、珠海三城。","gaokao_score":656,"tuition":5000,"employment_rate":93.8,"avg_salary":16500},
    {"id":13,"name":"Beijing Institute of Technology","cn":"北京理工大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"BT","score":582.4,"trend":"up","trendV":"+3.6","stars":4.5,"reviews":2580,"rank":13,"level":"985/211/双一流","type":"理工","metrics":{"学术":83.5,"科研":87.2,"就业":93.1,"国际化":73.8,"校园":83.2,"雇主声誉":88.3},"tags":[{"text":"985/211","type":"gold"},{"text":"兵器科技","type":"blue"},{"text":"工科强校","type":"cyan"}],"description":"北京理工大学，工信部直属，兵器科学与技术、控制科学与工程全国领先，理工科综合实力雄厚。","gaokao_score":655,"tuition":5000,"employment_rate":95.5,"avg_salary":17800},
    {"id":14,"name":"Harbin Institute of Technology","cn":"哈尔滨工业大学","loc":"黑龙江","region":"东北","country":"中国","logo":"#c40009","initials":"HB","score":576.4,"trend":"up","trendV":"+4.5","stars":4.6,"reviews":3180,"rank":14,"level":"985/211/双一流","type":"理工","metrics":{"学术":85.7,"科研":90.1,"就业":91.5,"国际化":72.8,"校园":84.3,"雇主声誉":89.4},"tags":[{"text":"985/211","type":"gold"},{"text":"航天土木","type":"blue"},{"text":"东北第一","type":"red"}],"description":"哈尔滨工业大学，航天领域先驱，焊接、工程力学全国第一，深圳、威海设有分校，本部在哈尔滨。","gaokao_score":653,"tuition":5000,"employment_rate":95.8,"avg_salary":17200},
    {"id":15,"name":"Sichuan University","cn":"四川大学","loc":"四川","region":"西南","country":"中国","logo":"#004687","initials":"SC","score":576.3,"trend":"up","trendV":"+3.1","stars":4.5,"reviews":3820,"rank":15,"level":"985/211/双一流","type":"综合","metrics":{"学术":80.2,"科研":81.5,"就业":87.2,"国际化":75.1,"校园":89.5,"雇主声誉":82.8},"tags":[{"text":"985/211","type":"gold"},{"text":"口腔顶尖","type":"red"},{"text":"西南第一","type":"orange"}],"description":"四川大学，西南最强综合性大学，口腔医学全国第一，文学、历史、轻工技术居全国前列。","gaokao_score":648,"tuition":5000,"employment_rate":93.2,"avg_salary":14200},
    {"id":16,"name":"Southeast University","cn":"东南大学","loc":"江苏","region":"华东","country":"中国","logo":"#930025","initials":"SE","score":575.0,"trend":"up","trendV":"+4.9","stars":4.6,"reviews":2890,"rank":16,"level":"985/211/双一流","type":"理工","metrics":{"学术":84.8,"科研":86.2,"就业":91.8,"国际化":74.5,"校园":87.8,"雇主声誉":87.1},"tags":[{"text":"985/211","type":"gold"},{"text":"建筑老八校","type":"orange"},{"text":"南京第二","type":"cyan"}],"description":"东南大学，建筑老八校之一，建筑学、土木工程、交通工程全国领先，前身南京工学院，工科底蕴深厚。","gaokao_score":655,"tuition":5000,"employment_rate":94.9,"avg_salary":17500},
    {"id":17,"name":"Renmin University of China","cn":"中国人民大学","loc":"北京","region":"华北","country":"中国","logo":"#c40009","initials":"RM","score":558.0,"trend":"up","trendV":"+2.3","stars":4.7,"reviews":2890,"rank":17,"level":"985/211/双一流","type":"综合","metrics":{"学术":87.5,"科研":82.1,"就业":93.8,"国际化":78.2,"校园":82.5,"雇主声誉":94.7},"tags":[{"text":"985/211","type":"gold"},{"text":"法学经济","type":"purple"},{"text":"人文社科强","type":"gold"}],"description":"中国人民大学，中国人文社会科学的一面旗帜，法学、经济学、金融学、新闻传播学居全国第一。","gaokao_score":667,"tuition":5000,"employment_rate":96.1,"avg_salary":20500},
    {"id":18,"name":"Tongji University","cn":"同济大学","loc":"上海","region":"华东","country":"中国","logo":"#c40009","initials":"TJ","score":547.7,"trend":"up","trendV":"+3.8","stars":4.6,"reviews":3280,"rank":18,"level":"985/211/双一流","type":"综合","metrics":{"学术":83.1,"科研":84.7,"就业":93.5,"国际化":88.9,"校园":88.2,"雇主声誉":89.8},"tags":[{"text":"985/211","type":"gold"},{"text":"建筑老八校","type":"orange"},{"text":"土木顶尖","type":"blue"}],"description":"同济大学，建筑老八校之一，土木工程、建筑学、城市规划全国领先，与德国联系紧密，国际化程度高。","gaokao_score":660,"tuition":5000,"employment_rate":95.4,"avg_salary":18200},
    {"id":19,"name":"Beijing Normal University","cn":"北京师范大学","loc":"北京","region":"华北","country":"中国","logo":"#00529b","initials":"BN","score":543.8,"trend":"up","trendV":"+2.7","stars":4.6,"reviews":2980,"rank":19,"level":"985/211/双一流","type":"师范","metrics":{"学术":85.2,"科研":82.8,"就业":90.1,"国际化":75.3,"校园":88.7,"雇主声誉":86.9},"tags":[{"text":"985/211","type":"gold"},{"text":"师范第一","type":"cyan"},{"text":"教育顶尖","type":"blue"}],"description":"北京师范大学，中国师范类大学排名第一，教育学、心理学、中国语言文学居全国第一，免费师范生政策。","gaokao_score":650,"tuition":4000,"employment_rate":94.2,"avg_salary":14800},
    {"id":20,"name":"Tianjin University","cn":"天津大学","loc":"天津","region":"华北","country":"中国","logo":"#c40009","initials":"TJ2","score":528.5,"trend":"up","trendV":"+3.4","stars":4.5,"reviews":2580,"rank":20,"level":"985/211/双一流","type":"理工","metrics":{"学术":81.7,"科研":83.9,"就业":90.8,"国际化":72.1,"校园":86.4,"雇主声誉":85.3},"tags":[{"text":"985/211","type":"gold"},{"text":"化工顶尖","type":"blue"},{"text":"天津第一","type":"red"}],"description":"天津大学，中国第一所现代大学，化学工程与技术全国第一，建筑学、水利工程实力雄厚。","gaokao_score":650,"tuition":5000,"employment_rate":94.1,"avg_salary":16500},

    # 21-40 优质985/211
    {"id":21,"name":"Northwestern Polytechnical University","cn":"西北工业大学","loc":"陕西","region":"西北","country":"中国","logo":"#003087","initials":"NW","score":513.7,"trend":"up","trendV":"+5.1","stars":4.5,"reviews":2310,"rank":21,"level":"985/211/双一流","type":"理工","metrics":{"学术":80.5,"科研":84.3,"就业":91.5,"国际化":68.2,"校园":81.8,"雇主声誉":86.4},"tags":[{"text":"985/211","type":"gold"},{"text":"航空航天","type":"blue"},{"text":"航海工程","type":"cyan"}],"description":"西北工业大学，工信部直属，航空宇航科学与技术、材料工程全国领先，三航特色鲜明。","gaokao_score":648,"tuition":5000,"employment_rate":95.2,"avg_salary":17200},
    {"id":22,"name":"Shandong University","cn":"山东大学","loc":"山东","region":"华东","country":"中国","logo":"#c40009","initials":"SD","score":513.4,"trend":"up","trendV":"+2.6","stars":4.4,"reviews":3480,"rank":22,"level":"985/211/双一流","type":"综合","metrics":{"学术":78.3,"科研":79.5,"就业":86.8,"国际化":71.4,"校园":88.9,"雇主声誉":81.2},"tags":[{"text":"985/211","type":"gold"},{"text":"数学强校","type":"purple"},{"text":"山东第一","type":"red"}],"description":"山东大学，山东省最强高校，数学、材料科学、临床医学居全国前列，规模最大的985大学之一。","gaokao_score":638,"tuition":5000,"employment_rate":92.5,"avg_salary":13800},
    {"id":23,"name":"Nankai University","cn":"南开大学","loc":"天津","region":"华北","country":"中国","logo":"#004687","initials":"NK","score":512.2,"trend":"up","trendV":"+1.8","stars":4.5,"reviews":2980,"rank":23,"level":"985/211/双一流","type":"综合","metrics":{"学术":82.4,"科研":80.1,"就业":89.2,"国际化":82.8,"校园":87.3,"雇主声誉":85.1},"tags":[{"text":"985/211","type":"gold"},{"text":"化学数学","type":"blue"},{"text":"天津第二","type":"cyan"}],"description":"南开大学，周恩来总理母校，化学、数学、统计学、经济学历史悠久，国际化程度高，天津双雄之一。","gaokao_score":650,"tuition":5000,"employment_rate":93.8,"avg_salary":16800},
    {"id":24,"name":"Xiamen University","cn":"厦门大学","loc":"福建","region":"华东","country":"中国","logo":"#c40009","initials":"XM","score":504.8,"trend":"up","trendV":"+3.2","stars":4.6,"reviews":3650,"rank":24,"level":"985/211/双一流","type":"综合","metrics":{"学术":79.1,"科研":77.8,"就业":87.5,"国际化":85.7,"校园":96.3,"雇主声誉":83.8},"tags":[{"text":"985/211","type":"gold"},{"text":"最美校园","type":"pink"},{"text":"会计顶尖","type":"purple"}],"description":"厦门大学，中国最美大学之一，会计学、经济学、海洋科学全国领先，与海外联系广泛，校园面朝大海。","gaokao_score":645,"tuition":5000,"employment_rate":93.1,"avg_salary":16200},
    {"id":25,"name":"China Agricultural University","cn":"中国农业大学","loc":"北京","region":"华北","country":"中国","logo":"#00529b","initials":"CA","score":499.2,"trend":"up","trendV":"+2.5","stars":4.4,"reviews":2180,"rank":25,"level":"985/211/双一流","type":"农业","metrics":{"学术":83.7,"科研":87.5,"就业":88.2,"国际化":72.3,"校园":85.6,"雇主声誉":80.5},"tags":[{"text":"985/211","type":"gold"},{"text":"农业顶尖","type":"green"},{"text":"食品科学","type":"orange"}],"description":"中国农业大学，农业与生命科学领域全国第一，畜牧学、兽医学、农业工程居世界前列，农林水最权威。","gaokao_score":628,"tuition":3000,"employment_rate":93.5,"avg_salary":14500},
    {"id":26,"name":"Jilin University","cn":"吉林大学","loc":"吉林","region":"东北","country":"中国","logo":"#c40009","initials":"JL","score":486.0,"trend":"up","trendV":"+3.8","stars":4.4,"reviews":3920,"rank":26,"level":"985/211/双一流","type":"综合","metrics":{"学术":76.8,"科研":78.2,"就业":85.3,"国际化":70.5,"校园":90.2,"雇主声誉":79.4},"tags":[{"text":"985/211","type":"gold"},{"text":"汽车工程","type":"blue"},{"text":"东北第二","type":"cyan"}],"description":"吉林大学，吉林省最强高校，法学、车辆工程、化学均为全国重点，校园面积全国最大。","gaokao_score":632,"tuition":5000,"employment_rate":91.8,"avg_salary":13500},
    {"id":27,"name":"Central South University","cn":"中南大学","loc":"湖南","region":"华中","country":"中国","logo":"#c40009","initials":"CS","score":485.3,"trend":"up","trendV":"+6.2","stars":4.5,"reviews":3120,"rank":27,"level":"985/211/双一流","type":"综合","metrics":{"学术":78.9,"科研":81.5,"就业":89.8,"国际化":69.8,"校园":85.1,"雇主声誉":83.2},"tags":[{"text":"985/211","type":"gold"},{"text":"有色金属","type":"blue"},{"text":"医学材料","type":"red"}],"description":"中南大学，材料科学、冶金工程、矿业工程全国领先，湘雅医学院与协和齐名，湖南最强。","gaokao_score":640,"tuition":5000,"employment_rate":94.2,"avg_salary":15500},
    {"id":28,"name":"Dalian University of Technology","cn":"大连理工大学","loc":"辽宁","region":"东北","country":"中国","logo":"#00529b","initials":"DL","score":469.5,"trend":"up","trendV":"+2.9","stars":4.5,"reviews":2780,"rank":28,"level":"985/211/双一流","type":"理工","metrics":{"学术":80.2,"科研":82.1,"就业":90.8,"国际化":73.4,"校园":88.5,"雇主声誉":84.6},"tags":[{"text":"985/211","type":"gold"},{"text":"化工力学","type":"blue"},{"text":"东北第三","type":"green"}],"description":"大连理工大学，化工与力学全国领先，机械设计制造及其自动化、软件工程实力雄厚，滨城求学体验佳。","gaokao_score":645,"tuition":5000,"employment_rate":94.8,"avg_salary":16200},
    {"id":29,"name":"Hunan University","cn":"湖南大学","loc":"湖南","region":"华中","country":"中国","logo":"#c40009","initials":"HN","score":466.4,"trend":"up","trendV":"+3.5","stars":4.4,"reviews":2980,"rank":29,"level":"985/211/双一流","type":"综合","metrics":{"学术":78.5,"科研":79.3,"就业":88.5,"国际化":70.2,"校园":87.9,"雇主声誉":82.8},"tags":[{"text":"985/211","type":"gold"},{"text":"土木机械","type":"blue"},{"text":"千年学府","type":"purple"}],"description":"湖南大学，岳麓书院延续千年，土木工程、国际贸易、设计学全国知名，中国最古老的现代大学之一。","gaokao_score":638,"tuition":5000,"employment_rate":93.1,"avg_salary":14800},
    {"id":30,"name":"East China Normal University","cn":"华东师范大学","loc":"上海","region":"华东","country":"中国","logo":"#00529b","initials":"EC","score":460.1,"trend":"up","trendV":"+2.4","stars":4.5,"reviews":2680,"rank":30,"level":"985/211/双一流","type":"师范","metrics":{"学术":81.3,"科研":79.8,"就业":89.5,"国际化":78.9,"校园":87.1,"雇主声誉":84.3},"tags":[{"text":"985/211","type":"gold"},{"text":"师范第二","type":"cyan"},{"text":"教育心理","type":"blue"}],"description":"华东师范大学，上海最强师范高校，教育学、心理学、地理学全国领先，与国际接轨程度高。","gaokao_score":648,"tuition":4000,"employment_rate":94.5,"avg_salary":15500},

    # 31-50 强势211
    {"id":31,"name":"Beijing University of Technology","cn":"北京工业大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"BJ","score":0,"trend":"up","trendV":"+1.8","stars":4.3,"reviews":1890,"rank":31,"level":"211/双一流","type":"理工","metrics":{"学术":75.2,"科研":76.8,"就业":90.5,"国际化":68.4,"校园":82.3,"雇主声誉":81.2},"tags":[{"text":"211","type":"blue"},{"text":"北京属","type":"red"},{"text":"计算机","type":"cyan"}],"description":"北京工业大学，北京市属最强理工科高校，计算机科学与技术、土木工程居全国前列，北京211性价比之选。","gaokao_score":638,"tuition":5000,"employment_rate":94.8,"avg_salary":17800},
    {"id":32,"name":"Shanghai University of Finance and Economics","cn":"上海财经大学","loc":"上海","region":"华东","country":"中国","logo":"#c40009","initials":"SF","score":0,"trend":"up","trendV":"+1.5","stars":4.6,"reviews":2280,"rank":32,"level":"211/双一流","type":"财经","metrics":{"学术":83.5,"科研":78.3,"就业":95.8,"国际化":84.2,"校园":80.5,"雇主声誉":92.8},"tags":[{"text":"211","type":"blue"},{"text":"财经顶尖","type":"gold"},{"text":"上海","type":"red"}],"description":"上海财经大学，经济学、会计学、金融学全国前三，顶级券商与四大会计师事务所Target School。","gaokao_score":662,"tuition":5000,"employment_rate":97.2,"avg_salary":22800},
    {"id":33,"name":"University of Science and Technology Beijing","cn":"北京科技大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"UST","score":0,"trend":"up","trendV":"+2.1","stars":4.3,"reviews":1980,"rank":33,"level":"211/双一流","type":"理工","metrics":{"学术":77.8,"科研":80.5,"就业":89.8,"国际化":69.5,"校园":83.1,"雇主声誉":83.7},"tags":[{"text":"211","type":"blue"},{"text":"冶金材料","type":"cyan"},{"text":"北京","type":"red"}],"description":"北京科技大学，冶金工程、材料科学与工程全国领先，前身北京钢铁学院，工科211实力派。","gaokao_score":632,"tuition":5000,"employment_rate":93.5,"avg_salary":16500},
    {"id":34,"name":"Beijing Jiaotong University","cn":"北京交通大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"BTJ","score":0,"trend":"up","trendV":"+2.3","stars":4.3,"reviews":1850,"rank":34,"level":"211/双一流","type":"理工","metrics":{"学术":76.5,"科研":78.9,"就业":91.2,"国际化":70.8,"校园":82.7,"雇主声誉":85.4},"tags":[{"text":"211","type":"blue"},{"text":"交通信息","type":"cyan"},{"text":"铁路工程","type":"blue"}],"description":"北京交通大学，交通运输工程、信息与通信工程全国前三，铁路与城市轨道交通领域顶尖211。","gaokao_score":635,"tuition":5000,"employment_rate":95.1,"avg_salary":17200},
    {"id":35,"name":"Nankai University (Extended)","cn":"苏州大学","loc":"江苏","region":"华东","country":"中国","logo":"#c40009","initials":"SZ","score":0,"trend":"up","trendV":"+4.2","stars":4.2,"reviews":2450,"rank":35,"level":"211/双一流","type":"综合","metrics":{"学术":74.8,"科研":76.2,"就业":87.5,"国际化":72.3,"校园":88.9,"雇主声誉":78.4},"tags":[{"text":"211","type":"blue"},{"text":"法学材料","type":"purple"},{"text":"江苏","type":"green"}],"description":"苏州大学，江苏省属最强211，法学、纺织工程、材料科学居全国前列，苏州经济发达就业机会多。","gaokao_score":625,"tuition":5000,"employment_rate":92.3,"avg_salary":14800},
    {"id":36,"name":"Southeast University (Nanjing)","cn":"南京航空航天大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"NA","score":0,"trend":"up","trendV":"+3.8","stars":4.4,"reviews":2180,"rank":36,"level":"211/双一流","type":"理工","metrics":{"学术":78.9,"科研":81.3,"就业":92.5,"国际化":68.9,"校园":84.5,"雇主声誉":86.2},"tags":[{"text":"211","type":"blue"},{"text":"航空航天","type":"cyan"},{"text":"南京","type":"green"}],"description":"南京航空航天大学，航空宇航科学与技术、力学全国领先，民航飞行员培养摇篮，江苏工科211。","gaokao_score":638,"tuition":5000,"employment_rate":95.8,"avg_salary":17500},
    {"id":37,"name":"Nanjing University of Aeronautics and Astronautics","cn":"南京理工大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"NL","score":0,"trend":"up","trendV":"+2.7","stars":4.3,"reviews":2080,"rank":37,"level":"211/双一流","type":"理工","metrics":{"学术":76.2,"科研":78.5,"就业":90.8,"国际化":67.2,"校园":83.8,"雇主声誉":83.1},"tags":[{"text":"211","type":"blue"},{"text":"兵器光电","type":"blue"},{"text":"南京","type":"green"}],"description":"南京理工大学，兵器科学与技术、化学工程与技术全国领先，前身哈军工炮兵工程系，江苏211。","gaokao_score":630,"tuition":5000,"employment_rate":94.2,"avg_salary":16200},
    {"id":38,"name":"Xiamen University (Extended)","cn":"华中师范大学","loc":"湖北","region":"华中","country":"中国","logo":"#00529b","initials":"HZ2","score":0,"trend":"up","trendV":"+2.1","stars":4.3,"reviews":2180,"rank":38,"level":"211/双一流","type":"师范","metrics":{"学术":77.5,"科研":75.8,"就业":88.2,"国际化":72.8,"校园":86.3,"雇主声誉":82.5},"tags":[{"text":"211","type":"blue"},{"text":"师范","type":"cyan"},{"text":"武汉","type":"orange"}],"description":"华中师范大学，教育部直属六所师范之一，政治学、教育学全国前列，免费师范生政策。","gaokao_score":625,"tuition":4000,"employment_rate":93.5,"avg_salary":13800},
    {"id":39,"name":"Harbin Institute of Technology (Weihai)","cn":"山东大学威海分校","loc":"山东","region":"华东","country":"中国","logo":"#c40009","initials":"SDW","score":0,"trend":"up","trendV":"+1.5","stars":4.2,"reviews":1650,"rank":39,"level":"985/211/双一流","type":"综合","metrics":{"学术":74.5,"科研":72.8,"就业":86.2,"国际化":78.5,"校园":90.2,"雇主声誉":75.8},"tags":[{"text":"985/211","type":"gold"},{"text":"威海","type":"cyan"},{"text":"中外合作","type":"purple"}],"description":"山东大学威海分校，与山东大学共享文凭，校区在威海，中外合作项目丰富，性价比优于本部。","gaokao_score":612,"tuition":8000,"employment_rate":91.5,"avg_salary":13200},
    {"id":40,"name":"Beijing Institute of Technology (Zhuhai)","cn":"北京理工大学珠海学院","loc":"广东","region":"华南","country":"中国","logo":"#003087","initials":"BIZ","score":0,"trend":"up","trendV":"+1.2","stars":4.1,"reviews":1520,"rank":40,"level":"独立学院","type":"理工","metrics":{"学术":68.5,"科研":65.2,"就业":84.3,"国际化":62.8,"校园":88.5,"雇主声誉":70.2},"tags":[{"text":"独立学院","type":"orange"},{"text":"珠海","type":"cyan"},{"text":"珠三角","type":"green"}],"description":"北京理工大学珠海学院，珠三角优质独立学院，依托北京理工大学资源，机械工程、计算机专业较强。","gaokao_score":538,"tuition":28000,"employment_rate":88.2,"avg_salary":10800},

    # 41-60 重点211
    {"id":41,"name":"Beijing Foreign Studies University","cn":"北京外国语大学","loc":"北京","region":"华北","country":"中国","logo":"#00529b","initials":"BF","score":0,"trend":"up","trendV":"+1.8","stars":4.5,"reviews":1850,"rank":41,"level":"211/双一流","type":"语言","metrics":{"学术":82.8,"科研":77.5,"就业":92.8,"国际化":95.3,"校园":79.8,"雇主声誉":90.5},"tags":[{"text":"211","type":"blue"},{"text":"外语顶尖","type":"purple"},{"text":"外交官摇篮","type":"gold"}],"description":"北京外国语大学，外语专业全国最多（101种外语），外交、经贸、翻译领域人才输送重镇。","gaokao_score":650,"tuition":6000,"employment_rate":96.5,"avg_salary":17500},
    {"id":42,"name":"Communication University of China","cn":"中国传媒大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"CC","score":0,"trend":"up","trendV":"+2.4","stars":4.4,"reviews":2180,"rank":42,"level":"211/双一流","type":"传媒","metrics":{"学术":80.5,"科研":76.8,"就业":93.5,"国际化":82.4,"校园":81.5,"雇主声誉":88.9},"tags":[{"text":"211","type":"blue"},{"text":"传媒顶尖","type":"red"},{"text":"播音主持","type":"gold"}],"description":"中国传媒大学，新闻传播学、广播电视艺术学全国第一，央视、新华社等媒体人才输送基地。","gaokao_score":645,"tuition":6000,"employment_rate":95.2,"avg_salary":16500},
    {"id":43,"name":"University of International Business and Economics","cn":"对外经济贸易大学","loc":"北京","region":"华北","country":"中国","logo":"#004687","initials":"UI","score":0,"trend":"up","trendV":"+1.9","stars":4.6,"reviews":2080,"rank":43,"level":"211/双一流","type":"财经","metrics":{"学术":82.1,"科研":76.5,"就业":96.2,"国际化":91.8,"校园":80.8,"雇主声誉":93.4},"tags":[{"text":"211","type":"blue"},{"text":"经贸顶尖","type":"gold"},{"text":"外贸黄埔","type":"purple"}],"description":"对外经济贸易大学，国际贸易、金融学全国领先，外资企业与四大会计师事务所Target School。","gaokao_score":658,"tuition":5000,"employment_rate":97.1,"avg_salary":21500},
    {"id":44,"name":"China University of Political Science and Law","cn":"中国政法大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"CU","score":0,"trend":"up","trendV":"+1.6","stars":4.5,"reviews":1920,"rank":44,"level":"211/双一流","type":"政法","metrics":{"学术":84.2,"科研":79.3,"就业":91.5,"国际化":78.9,"校园":79.5,"雇主声誉":89.2},"tags":[{"text":"211","type":"blue"},{"text":"法学顶尖","type":"gold"},{"text":"政法黄埔","type":"red"}],"description":"中国政法大学，法学、政治学、社会学全国第一，公检法系统人才输送核心院校。","gaokao_score":652,"tuition":5000,"employment_rate":94.8,"avg_salary":17500},
    {"id":45,"name":"Central Conservatory of Music","cn":"中央音乐学院","loc":"北京","region":"华北","country":"中国","logo":"#c40009","initials":"CM","score":0,"trend":"up","trendV":"+1.0","stars":4.7,"reviews":890,"rank":45,"level":"211/双一流","type":"艺术","metrics":{"学术":88.5,"科研":72.3,"就业":87.2,"国际化":85.2,"校园":85.3,"雇主声誉":88.5},"tags":[{"text":"211","type":"blue"},{"text":"音乐顶尖","type":"gold"},{"text":"艺术类最高","type":"pink"}],"description":"中央音乐学院，中国音乐最高学府，音乐学、作曲与作曲技术理论全国第一，艺术类院校最高殿堂。","gaokao_score":585,"tuition":10000,"employment_rate":88.5,"avg_salary":12800},
    {"id":46,"name":"Shanghai International Studies University","cn":"上海外国语大学","loc":"上海","region":"华东","country":"中国","logo":"#00529b","initials":"SS","score":0,"trend":"up","trendV":"+2.2","stars":4.5,"reviews":1980,"rank":46,"level":"211/双一流","type":"语言","metrics":{"学术":81.5,"科研":75.8,"就业":93.8,"国际化":93.5,"校园":82.3,"雇主声誉":90.1},"tags":[{"text":"211","type":"blue"},{"text":"外语顶尖","type":"purple"},{"text":"上海","type":"red"}],"description":"上海外国语大学，外语专业与对外经贸并重，多语种+金融复合型人才培养特色鲜明。","gaokao_score":648,"tuition":6000,"employment_rate":96.2,"avg_salary":18500},
    {"id":47,"name":"Xiamen University (Law)","cn":"西安电子科技大学","loc":"陕西","region":"西北","country":"中国","logo":"#003087","initials":"XD","score":0,"trend":"up","trendV":"+3.5","stars":4.4,"reviews":2380,"rank":47,"level":"211/双一流","type":"理工","metrics":{"学术":77.8,"科研":80.5,"就业":93.2,"国际化":68.5,"校园":82.8,"雇主声誉":87.5},"tags":[{"text":"211","type":"blue"},{"text":"电子信息","type":"cyan"},{"text":"两电一邮","type":"blue"}],"description":"西安电子科技大学，电子信息领域两电一邮成员，信息与通信工程、计算机科学全国前三，华为招聘重镇。","gaokao_score":635,"tuition":5000,"employment_rate":95.8,"avg_salary":18800},
    {"id":48,"name":"University of Electronic Science and Technology","cn":"电子科技大学","loc":"四川","region":"西南","country":"中国","logo":"#003087","initials":"UE","score":0,"trend":"up","trendV":"+3.2","stars":4.5,"reviews":2580,"rank":48,"level":"211/双一流","type":"理工","metrics":{"学术":79.8,"科研":83.5,"就业":94.5,"国际化":72.1,"校园":84.2,"雇主声誉":89.3},"tags":[{"text":"211","type":"blue"},{"text":"电子信息","type":"cyan"},{"text":"两电一邮","type":"blue"}],"description":"电子科技大学，两电一邮之首，电子科学与技术、信息与通信工程全国第一，西部硅谷人才摇篮。","gaokao_score":648,"tuition":5000,"employment_rate":96.5,"avg_salary":19800},
    {"id":49,"name":"Beijing University of Posts and Telecommunications","cn":"北京邮电大学","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"BP","score":0,"trend":"up","trendV":"+2.8","stars":4.5,"reviews":2280,"rank":49,"level":"211/双一流","type":"理工","metrics":{"学术":78.5,"科研":81.2,"就业":95.8,"国际化":71.8,"校园":81.5,"雇主声誉":91.2},"tags":[{"text":"211","type":"blue"},{"text":"通信信息","type":"cyan"},{"text":"两电一邮","type":"blue"}],"description":"北京邮电大学，两电一邮成员，通信工程、信息与通信工程全国前三，移动联通电信招聘重镇。","gaokao_score":648,"tuition":5000,"employment_rate":97.1,"avg_salary":20500},
    {"id":50,"name":"Southeast University (SE)","cn":"南京信息工程大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"NJ2","score":0,"trend":"up","trendV":"+3.5","stars":4.2,"reviews":1950,"rank":50,"level":"双一流","type":"理工","metrics":{"学术":75.8,"科研":77.2,"就业":88.5,"国际化":68.9,"校园":85.8,"雇主声誉":78.3},"tags":[{"text":"双一流","type":"cyan"},{"text":"大气科学","type":"blue"},{"text":"气象顶尖","type":"green"}],"description":"南京信息工程大学，大气科学全国第一，气象学领域最高学府，双一流学科建设高校。","gaokao_score":612,"tuition":5000,"employment_rate":92.8,"avg_salary":14200},

    # 51-65 特色211
    {"id":51,"name":"Fudan University (Finance)","cn":"上海大学","loc":"上海","region":"华东","country":"中国","logo":"#c40009","initials":"SHU","score":0,"trend":"up","trendV":"+2.1","stars":4.3,"reviews":2480,"rank":51,"level":"211/双一流","type":"综合","metrics":{"学术":74.2,"科研":75.8,"就业":89.8,"国际化":79.3,"校园":86.5,"雇主声誉":81.5},"tags":[{"text":"211","type":"blue"},{"text":"上海","type":"red"},{"text":"机械自动化","type":"blue"}],"description":"上海大学，上海市属最强211，机械工程、社会学、美术学居全国前列，上海本地认可度高。","gaokao_score":635,"tuition":5000,"employment_rate":94.2,"avg_salary":17200},
    {"id":52,"name":"Beijing Normal University (Zhuhai)","cn":"北京师范大学珠海分校","loc":"广东","region":"华南","country":"中国","logo":"#00529b","initials":"BNZ","score":0,"trend":"up","trendV":"+1.8","stars":4.2,"reviews":1720,"rank":52,"level":"独立学院","type":"师范","metrics":{"学术":71.5,"科研":68.2,"就业":86.3,"国际化":82.5,"校园":92.5,"雇主声誉":75.2},"tags":[{"text":"独立学院","type":"orange"},{"text":"珠海","type":"cyan"},{"text":"师范特色","type":"blue"}],"description":"北京师范大学珠海分校，优质独立学院，心理学、教育学特色，依托北师大资源，性价比优。","gaokao_score":545,"tuition":22000,"employment_rate":89.5,"avg_salary":11200},
    {"id":53,"name":"Zhejiang University (Nanjing)","cn":"江南大学","loc":"江苏","region":"华东","country":"中国","logo":"#c40009","initials":"JN","score":0,"trend":"up","trendV":"+2.5","stars":4.2,"reviews":1850,"rank":53,"level":"211/双一流","type":"理工","metrics":{"学术":75.8,"科研":77.3,"就业":88.8,"国际化":69.5,"校园":87.2,"雇主声誉":79.4},"tags":[{"text":"211","type":"blue"},{"text":"食品科学","type":"green"},{"text":"轻工明珠","type":"orange"}],"description":"江南大学，食品科学与工程全国第一，发酵工程、工业设计国内领先，轻工特色鲜明。","gaokao_score":618,"tuition":5000,"employment_rate":92.8,"avg_salary":14500},
    {"id":54,"name":"China University of Petroleum","cn":"中国石油大学（北京）","loc":"北京","region":"华北","country":"中国","logo":"#003087","initials":"CP","score":0,"trend":"up","trendV":"+1.5","stars":4.2,"reviews":1680,"rank":54,"level":"211/双一流","type":"理工","metrics":{"学术":75.2,"科研":78.5,"就业":91.2,"国际化":67.8,"校园":81.8,"雇主声誉":80.5},"tags":[{"text":"211","type":"blue"},{"text":"石油化工","type":"blue"},{"text":"能源行业","type":"green"}],"description":"中国石油大学（北京），石油与天然气工程全国第一，能源行业就业稳定，中石油中石化招聘重镇。","gaokao_score":620,"tuition":5000,"employment_rate":94.5,"avg_salary":16200},
    {"id":55,"name":"Chongqing University","cn":"重庆大学","loc":"重庆","region":"西南","country":"中国","logo":"#c40009","initials":"CQ","score":0,"trend":"up","trendV":"+2.8","stars":4.3,"reviews":2980,"rank":55,"level":"985/211/双一流","type":"综合","metrics":{"学术":76.8,"科研":78.2,"就业":88.5,"国际化":70.8,"校园":88.9,"雇主声誉":82.3},"tags":[{"text":"985/211","type":"gold"},{"text":"电气建筑","type":"blue"},{"text":"重庆第一","type":"red"}],"description":"重庆大学，西南重要综合性985，电气工程、建筑学、机械工程居全国前列，重庆直辖市唯一985。","gaokao_score":638,"tuition":5000,"employment_rate":93.2,"avg_salary":14800},
    {"id":56,"name":"Kunming University of Science and Technology","cn":"昆明理工大学","loc":"云南","region":"西南","country":"中国","logo":"#003087","initials":"KM","score":0,"trend":"up","trendV":"+3.1","stars":4.1,"reviews":1820,"rank":56,"level":"省属重点","type":"理工","metrics":{"学术":72.5,"科研":74.8,"就业":86.5,"国际化":62.3,"校园":89.5,"雇主声誉":75.8},"tags":[{"text":"省属重点","type":"green"},{"text":"有色冶金","type":"blue"},{"text":"云南第一","type":"orange"}],"description":"昆明理工大学，云南省最强理工科高校，有色金属冶金、材料科学居全国前列，南亚留学首选。","gaokao_score":575,"tuition":4000,"employment_rate":89.8,"avg_salary":11500},
    {"id":57,"name":"Southwest University","cn":"西南大学","loc":"重庆","region":"西南","country":"中国","logo":"#00529b","initials":"SW","score":0,"trend":"up","trendV":"+2.2","stars":4.3,"reviews":2380,"rank":57,"level":"211/双一流","type":"师范","metrics":{"学术":75.8,"科研":76.5,"就业":87.2,"国际化":68.5,"校园":89.8,"雇主声誉":79.3},"tags":[{"text":"211","type":"blue"},{"text":"师范","type":"cyan"},{"text":"心理教育","type":"purple"}],"description":"西南大学，心理学、教育学全国前列，农学特色鲜明，重庆市属最大211，免费师范生名额多。","gaokao_score":615,"tuition":4000,"employment_rate":91.5,"avg_salary":12800},
    {"id":58,"name":"Southeast University (Extended)","cn":"河海大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"HH","score":0,"trend":"up","trendV":"+2.6","stars":4.2,"reviews":1880,"rank":58,"level":"211/双一流","type":"理工","metrics":{"学术":75.2,"科研":77.8,"就业":89.5,"国际化":68.2,"校园":84.5,"雇主声誉":81.2},"tags":[{"text":"211","type":"blue"},{"text":"水利水电","type":"cyan"},{"text":"工程管理","type":"blue"}],"description":"河海大学，水利工程、环境科学与工程全国前三，水利行业黄埔军校，三峡电站人才摇篮。","gaokao_score":622,"tuition":5000,"employment_rate":93.8,"avg_salary":15500},
    {"id":59,"name":"Harbin Engineering University","cn":"哈尔滨工程大学","loc":"黑龙江","region":"东北","country":"中国","logo":"#003087","initials":"HE","score":0,"trend":"up","trendV":"+2.4","stars":4.3,"reviews":1780,"rank":59,"level":"211/双一流","type":"理工","metrics":{"学术":76.5,"科研":79.2,"就业":90.8,"国际化":67.5,"校园":83.8,"雇主声誉":83.4},"tags":[{"text":"211","type":"blue"},{"text":"船舶海洋","type":"cyan"},{"text":"三海一核","type":"blue"}],"description":"哈尔滨工程大学，船舶与海洋工程、核科学与技术全国领先，三海一核（船舶、海军、核工业、海洋开发）特色。","gaokao_score":625,"tuition":5000,"employment_rate":94.5,"avg_salary":16200},
    {"id":60,"name":"Wuhan University of Technology","cn":"武汉理工大学","loc":"湖北","region":"华中","country":"中国","logo":"#003087","initials":"WL","score":0,"trend":"up","trendV":"+3.0","stars":4.2,"reviews":2180,"rank":60,"level":"211/双一流","type":"理工","metrics":{"学术":74.5,"科研":76.8,"就业":89.2,"国际化":66.8,"校园":85.3,"雇主声誉":80.5},"tags":[{"text":"211","type":"blue"},{"text":"材料交通","type":"blue"},{"text":"硅酸盐材料","type":"cyan"}],"description":"武汉理工大学，材料科学、交通运输工程全国前列，硅酸盐材料、船舶与海洋工程优势突出。","gaokao_score":615,"tuition":5000,"employment_rate":93.2,"avg_salary":14800},

    # 61-80 区域强校
    {"id":61,"name":"Nanjing Tech University","cn":"南京工业大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"NT","score":0,"trend":"up","trendV":"+2.8","stars":4.1,"reviews":1650,"rank":61,"level":"省属重点","type":"理工","metrics":{"学术":72.8,"科研":75.2,"就业":88.5,"国际化":65.3,"校园":86.8,"雇主声誉":77.4},"tags":[{"text":"省属重点","type":"green"},{"text":"化工建筑","type":"blue"},{"text":"江苏工科","type":"cyan"}],"description":"南京工业大学，化学工程与技术、建筑学居全国前列，江苏省属工科强校，就业质量优良。","gaokao_score":598,"tuition":4000,"employment_rate":92.1,"avg_salary":13500},
    {"id":62,"name":"Shanghai University of Engineering Science","cn":"上海工程技术大学","loc":"上海","region":"华东","country":"中国","logo":"#003087","initials":"SEU2","score":0,"trend":"up","trendV":"+1.5","stars":4.0,"reviews":1280,"rank":62,"level":"市属本科","type":"理工","metrics":{"学术":68.5,"科研":66.2,"就业":89.8,"国际化":72.5,"校园":83.2,"雇主声誉":75.3},"tags":[{"text":"市属本科","type":"green"},{"text":"航空航天","type":"blue"},{"text":"上海","type":"red"}],"description":"上海工程技术大学，上海市属高校，轨道交通、航空运输管理特色鲜明，上海本地就业优势明显。","gaokao_score":528,"tuition":5000,"employment_rate":90.5,"avg_salary":12800},
    {"id":63,"name":"Guangxi University","cn":"广西大学","loc":"广西","region":"华南","country":"中国","logo":"#c40009","initials":"GX","score":0,"trend":"up","trendV":"+1.8","stars":4.0,"reviews":1680,"rank":63,"level":"211/双一流","type":"综合","metrics":{"学术":70.5,"科研":72.3,"就业":84.5,"国际化":62.8,"校园":87.5,"雇主声誉":73.5},"tags":[{"text":"211","type":"blue"},{"text":"广西第一","type":"green"},{"text":"电气土木","type":"blue"}],"description":"广西大学，广西唯一211，电气工程、土木工程区域领先，广西本地就业市场主导者，东南亚交流机会多。","gaokao_score":572,"tuition":4000,"employment_rate":87.8,"avg_salary":10800},
    {"id":64,"name":"Guangxi University (Extended)","cn":"海南大学","loc":"海南","region":"华南","country":"中国","logo":"#c40009","initials":"HN2","score":0,"trend":"up","trendV":"+2.0","stars":4.1,"reviews":1380,"rank":64,"level":"211/双一流","type":"综合","metrics":{"学术":69.8,"科研":71.5,"就业":84.8,"国际化":72.8,"校园":91.5,"雇主声誉":72.8},"tags":[{"text":"211","type":"blue"},{"text":"海南","type":"cyan"},{"text":"旅游法学","type":"purple"}],"description":"海南大学，海南唯一211，海洋科学、旅游管理、法学特色明显，自贸港建设带来大量就业机遇。","gaokao_score":565,"tuition":4000,"employment_rate":88.2,"avg_salary":11500},
    {"id":65,"name":"Xinjiang University","cn":"新疆大学","loc":"新疆","region":"西北","country":"中国","logo":"#003087","initials":"XJ","score":0,"trend":"up","trendV":"+1.5","stars":4.0,"reviews":1120,"rank":65,"level":"211/双一流","type":"综合","metrics":{"学术":68.2,"科研":70.5,"就业":83.5,"国际化":58.3,"校园":86.8,"雇主声誉":70.2},"tags":[{"text":"211","type":"blue"},{"text":"新疆第一","type":"orange"},{"text":"民族特色","type":"purple"}],"description":"新疆大学，新疆唯一211，计算机、马克思主义理论民族学区域特色，一带一路核心区域留学就业机遇。","gaokao_score":548,"tuition":3500,"employment_rate":85.5,"avg_salary":9800},
    {"id":66,"name":"Ningbo University","cn":"宁波大学","loc":"浙江","region":"华东","country":"中国","logo":"#003087","initials":"NB","score":0,"trend":"up","trendV":"+2.5","stars":4.1,"reviews":1550,"rank":66,"level":"省属重点","type":"综合","metrics":{"学术":72.3,"科研":73.8,"就业":87.5,"国际化":78.5,"校园":88.9,"雇主声誉":76.8},"tags":[{"text":"省属重点","type":"green"},{"text":"力学水产","type":"blue"},{"text":"浙江","type":"red"}],"description":"宁波大学，力学、水产养殖学全国前列，浙江省属重点，宁波经济发达就业机会多，中外合作丰富。","gaokao_score":608,"tuition":5000,"employment_rate":91.8,"avg_salary":13800},
    {"id":67,"name":"Jiangxi Normal University","cn":"江西师范大学","loc":"江西","region":"华东","country":"中国","logo":"#00529b","initials":"JX","score":0,"trend":"up","trendV":"+1.8","stars":4.0,"reviews":1580,"rank":67,"level":"省属重点","type":"师范","metrics":{"学术":72.5,"科研":71.8,"就业":86.5,"国际化":62.3,"校园":87.2,"雇主声誉":76.2},"tags":[{"text":"省属重点","type":"green"},{"text":"师范","type":"cyan"},{"text":"江西第一","type":"blue"}],"description":"江西师范大学，江西省最强师范高校，化学、英语、汉语言文学师范特色，免费师范生政策。","gaokao_score":575,"tuition":4000,"employment_rate":90.2,"avg_salary":11200},
    {"id":68,"name":"Northwest University","cn":"西北大学","loc":"陕西","region":"西北","country":"中国","logo":"#c40009","initials":"NW2","score":0,"trend":"up","trendV":"+2.1","stars":4.1,"reviews":1680,"rank":68,"level":"省属重点","type":"综合","metrics":{"学术":74.5,"科研":76.2,"就业":86.8,"国际化":63.5,"校园":86.5,"雇主声誉":77.8},"tags":[{"text":"省属重点","type":"green"},{"text":"考古地质","type":"purple"},{"text":"陕西","type":"red"}],"description":"西北大学，考古学、地质学全国前三，经济学、历史学特色，陕西省属综合性大学最高水平。","gaokao_score":585,"tuition":4000,"employment_rate":89.5,"avg_salary":12500},
    {"id":69,"name":"Shandong Normal University","cn":"山东师范大学","loc":"山东","region":"华东","country":"中国","logo":"#00529b","initials":"SD2","score":0,"trend":"up","trendV":"+1.6","stars":4.0,"reviews":1680,"rank":69,"level":"省属重点","type":"师范","metrics":{"学术":72.8,"科研":71.5,"就业":86.2,"国际化":60.5,"校园":87.8,"雇主声誉":76.5},"tags":[{"text":"省属重点","type":"green"},{"text":"师范","type":"cyan"},{"text":"山东","type":"red"}],"description":"山东师范大学，山东省最强师范高校，心理学、教育学特色，免费师范生政策，山东本地就业认可度高。","gaokao_score":568,"tuition":4000,"employment_rate":90.5,"avg_salary":11500},
    {"id":70,"name":"Henan University","cn":"河南大学","loc":"河南","region":"华中","country":"中国","logo":"#c40009","initials":"HENU","score":0,"trend":"up","trendV":"+2.3","stars":4.1,"reviews":1780,"rank":70,"level":"双一流","type":"综合","metrics":{"学术":73.5,"科研":72.8,"就业":85.8,"国际化":62.8,"校园":89.2,"雇主声誉":76.8},"tags":[{"text":"双一流","type":"cyan"},{"text":"生物学","type":"blue"},{"text":"河南","type":"red"}],"description":"河南大学，生物学、历史学全国前列，双一流学科建设高校，河南省属综合大学最高水平。","gaokao_score":580,"tuition":4000,"employment_rate":89.2,"avg_salary":11800},

    # 71-80 更多区域强校
    {"id":71,"name":"Hefei University of Technology","cn":"合肥工业大学","loc":"安徽","region":"华东","country":"中国","logo":"#003087","initials":"HF","score":0,"trend":"up","trendV":"+2.7","stars":4.2,"reviews":1880,"rank":71,"level":"211/双一流","type":"理工","metrics":{"学术":75.8,"科研":77.5,"就业":90.2,"国际化":65.8,"校园":84.5,"雇主声誉":82.4},"tags":[{"text":"211","type":"blue"},{"text":"管理工程","type":"blue"},{"text":"安徽工科","type":"cyan"}],"description":"合肥工业大学，管理科学与工程、仪器科学全国领先，安徽工科211性价比之选。","gaokao_score":618,"tuition":5000,"employment_rate":93.5,"avg_salary":15200},
    {"id":72,"name":"Chengdu University of Technology","cn":"成都理工大学","loc":"四川","region":"西南","country":"中国","logo":"#003087","initials":"CDT","score":0,"trend":"up","trendV":"+2.9","stars":4.1,"reviews":1480,"rank":72,"level":"双一流","type":"理工","metrics":{"学术":73.2,"科研":75.8,"就业":87.2,"国际化":60.5,"校园":86.3,"雇主声誉":76.2},"tags":[{"text":"双一流","type":"cyan"},{"text":"地质能源","type":"blue"},{"text":"成都","type":"red"}],"description":"成都理工大学，地质学、核科学与技术全国前列，双一流学科建设，地质灾害研究领先。","gaokao_score":588,"tuition":4000,"employment_rate":90.5,"avg_salary":13200},
    {"id":73,"name":"Guangxi University (Science)","cn":"贵州大学","loc":"贵州","region":"西南","country":"中国","logo":"#c40009","initials":"GZU","score":0,"trend":"up","trendV":"+1.5","stars":4.0,"reviews":1380,"rank":73,"level":"211/双一流","type":"综合","metrics":{"学术":69.5,"科研":71.2,"就业":83.8,"国际化":58.9,"校园":87.5,"雇主声誉":72.3},"tags":[{"text":"211","type":"blue"},{"text":"贵州第一","type":"green"},{"text":"植保农药","type":"green"}],"description":"贵州大学，贵州省唯一211，植物保护、农药学特色，大数据产业发展迅速，贵州省属高校最高水平。","gaokao_score":552,"tuition":3500,"employment_rate":86.5,"avg_salary":10200},
    {"id":74,"name":"Liaoning University","cn":"辽宁大学","loc":"辽宁","region":"东北","country":"中国","logo":"#c40009","initials":"LNU","score":0,"trend":"up","trendV":"+1.8","stars":4.1,"reviews":1580,"rank":74,"level":"211/双一流","type":"综合","metrics":{"学术":72.8,"科研":73.5,"就业":86.5,"国际化":64.5,"校园":85.8,"雇主声誉":77.5},"tags":[{"text":"211","type":"blue"},{"text":"经济学","type":"purple"},{"text":"辽宁","type":"cyan"}],"description":"辽宁大学，应用经济学、法学特色，辽宁省属211，文科综合实力较强，沈阳就业市场广阔。","gaokao_score":585,"tuition":4000,"employment_rate":89.8,"avg_salary":12200},
    {"id":75,"name":"Hebei University of Technology","cn":"河北工业大学","loc":"天津","region":"华北","country":"中国","logo":"#003087","initials":"HB2","score":0,"trend":"up","trendV":"+2.0","stars":4.1,"reviews":1550,"rank":75,"level":"211/双一流","type":"理工","metrics":{"学术":73.5,"科研":75.2,"就业":88.8,"国际化":63.8,"校园":84.2,"雇主声誉":79.4},"tags":[{"text":"211","type":"blue"},{"text":"电气材料","type":"blue"},{"text":"天津","type":"red"}],"description":"河北工业大学，唯一在省外办学的211（在天津），电气工程、材料科学居全国前列，河北考生首选。","gaokao_score":598,"tuition":5000,"employment_rate":92.5,"avg_salary":14800},
    {"id":76,"name":"Dongbei University","cn":"东北大学","loc":"辽宁","region":"东北","country":"中国","logo":"#003087","initials":"NE","score":0,"trend":"up","trendV":"+2.5","stars":4.3,"reviews":2480,"rank":76,"level":"985/211/双一流","type":"理工","metrics":{"学术":76.5,"科研":79.8,"就业":90.5,"国际化":69.2,"校园":86.8,"雇主声誉":84.3},"tags":[{"text":"985/211","type":"gold"},{"text":"自动化","type":"blue"},{"text":"东北第三","type":"cyan"}],"description":"东北大学，自动化、计算机科学与技术全国前列，985梯队中性价比最高，沈阳产业转型机会多。","gaokao_score":632,"tuition":5000,"employment_rate":94.2,"avg_salary":16500},
    {"id":77,"name":"Beijing Forestry University","cn":"北京林业大学","loc":"北京","region":"华北","country":"中国","logo":"#00529b","initials":"BFU","score":0,"trend":"up","trendV":"+1.2","stars":4.2,"reviews":1280,"rank":77,"level":"211/双一流","type":"农林","metrics":{"学术":76.8,"科研":80.5,"就业":86.8,"国际化":68.5,"校园":90.8,"雇主声誉":77.8},"tags":[{"text":"211","type":"blue"},{"text":"林业园林","type":"green"},{"text":"生态环保","type":"cyan"}],"description":"北京林业大学，林学、风景园林学全国第一，生态环保行业人才输送基地，北京211中性价比高。","gaokao_score":605,"tuition":4000,"employment_rate":90.8,"avg_salary":13500},
    {"id":78,"name":"Huazhong Agricultural University","cn":"华中农业大学","loc":"湖北","region":"华中","country":"中国","logo":"#00529b","initials":"HZAU","score":0,"trend":"up","trendV":"+1.8","stars":4.2,"reviews":1380,"rank":78,"level":"211/双一流","type":"农业","metrics":{"学术":76.2,"科研":79.8,"就业":87.5,"国际化":65.3,"校园":88.9,"雇主声誉":78.3},"tags":[{"text":"211","type":"blue"},{"text":"农学畜牧","type":"green"},{"text":"生物育种","type":"cyan"}],"description":"华中农业大学，作物学、畜牧学全国前列，生物学、农业工程优势明显，农业科技人才摇篮。","gaokao_score":595,"tuition":3000,"employment_rate":91.2,"avg_salary":12800},
    {"id":79,"name":"Shaanxi Normal University","cn":"陕西师范大学","loc":"陕西","region":"西北","country":"中国","logo":"#00529b","initials":"SNU","score":0,"trend":"up","trendV":"+1.5","stars":4.1,"reviews":1480,"rank":79,"level":"211/双一流","type":"师范","metrics":{"学术":74.5,"科研":72.8,"就业":86.8,"国际化":62.3,"校园":87.5,"雇主声誉":78.2},"tags":[{"text":"211","type":"blue"},{"text":"师范","type":"cyan"},{"text":"历史中文","type":"purple"}],"description":"陕西师范大学，西部最强师范高校，中国语言文学、历史学特色，免费师范生政策，西安就业机会多。","gaokao_score":590,"tuition":4000,"employment_rate":90.5,"avg_salary":11800},
    {"id":80,"name":"China Pharmaceutical University","cn":"中国药科大学","loc":"江苏","region":"华东","country":"中国","logo":"#003087","initials":"CPU","score":0,"trend":"up","trendV":"+1.8","stars":4.3,"reviews":1380,"rank":80,"level":"211/双一流","type":"医药","metrics":{"学术":80.5,"科研":83.2,"就业":92.5,"国际化":70.5,"校园":83.5,"雇主声誉":85.8},"tags":[{"text":"211","type":"blue"},{"text":"药学顶尖","type":"red"},{"text":"医药黄埔","type":"gold"}],"description":"中国药科大学，药学、中药学全国第一，药物制剂、临床药学行业标杆，医药行业核心人才输出地。","gaokao_score":628,"tuition":5000,"employment_rate":95.8,"avg_salary":17200},
]

# 专业分类（与高考专业组对应）
PROGRAMS = [
    {"name":"计算机类","icon":"💻","univs":["清华大学","北京大学","浙江大学","上海交通大学","复旦大学","南京大学","中国科学技术大学","华中科技大学","北京航空航天大学","电子科技大学","西安电子科技大学","北京邮电大学","哈尔滨工业大学","北京理工大学","武汉大学","中山大学","四川大学","北京师范大学","同济大学","华东师范大学","中国人民大学","东南大学","西北工业大学","南京航空航天大学","南京理工大学","北京交通大学","北京科技大学","北京工业大学","合肥工业大学","武汉理工大学","苏州大学","南京信息工程大学","上海大学","山东大学","吉林大学","湖南大学","大连理工大学","重庆大学","西南大学","江南大学","东北大学","深圳大学","杭州电子科技大学","重庆邮电大学","北京化工大学","华东理工大学","哈尔滨工程大学","河海大学","中国矿业大学","长安大学","兰州大学","云南大学","福州大学","南昌大学","安徽大学","郑州大学","广西大学","海南大学","贵州大学","辽宁大学","河北工业大学","宁波大学","西安建筑科技大学","南京工业大学","浙江工业大学","杭州师范大学","华南师范大学","广州大学","广东工业大学","深圳大学","成都理工大学","昆明理工大学","东北师范大学","陕西师范大学","山东师范大学","福建师范大学","华中师范大学","北京林业大学","华中农业大学","中国农业大学","南京农业大学","西北农林科技大学","北京中医药大学","上海中医药大学","天津医科大学","哈尔滨医科大学","重庆医科大学","南京医科大学","广州医科大学","中国药科大学","沈阳药科大学","上海音乐学院","中央音乐学院","中国美术学院","中央美术学院","北京体育大学","上海体育学院","武汉体育学院","天津体育学院","对外经济贸易大学","上海外国语大学","北京外国语大学","中国政法大学","华东政法大学","西南政法大学","中央财经大学","西南财经大学","中南财经政法大学","东北财经大学","江西财经大学","南京审计大学","上海对外经贸大学","北京语言大学","华南理工大学","暨南大学","华侨大学","厦门大学","深圳北理莫斯科大学","昆山杜克大学","西交利物浦大学","宁波诺丁汉大学"]},
    {"name":"电子信息类","icon":"📡","univs":["清华大学","北京大学","上海交通大学","复旦大学","东南大学","电子科技大学","北京邮电大学","西安电子科技大学","北京航空航天大学","南京大学","浙江大学","华中科技大学","武汉大学","哈尔滨工业大学","北京理工大学","北京交通大学","北京科技大学","哈尔滨工程大学","南京航空航天大学","南京理工大学","西北工业大学","西安交通大学","北京工业大学","合肥工业大学","华东师范大学","同济大学","南开大学","天津大学","四川大学","重庆大学","中山大学","华南理工大学","深圳大学","杭州电子科技大学","重庆邮电大学","北京化工大学","华东理工大学","武汉理工大学","哈尔滨理工大学","南京信息工程大学","江苏大学","扬州大学","宁波大学","杭州师范大学","浙江工业大学","安徽大学","福州大学","南昌大学","郑州大学","广西大学","海南大学","贵州大学","云南大学","兰州大学","新疆大学","东北师范大学","陕西师范大学","山东师范大学","福建师范大学","华中师范大学","辽宁师范大学","河南大学","山西大学","河北工业大学","燕山大学","中北大学","沈阳航空航天大学","沈阳理工大学","长春理工大学","哈尔滨工程大学","河海大学","中国矿业大学","江苏科技大学","南通大学","温州大学","华侨大学","暨南大学","厦门大学","深圳北理莫斯科大学","西交利物浦大学","宁波诺丁汉大学"]},
    {"name":"自动化类","icon":"🤖","univs":["清华大学","浙江大学","上海交通大学","华中科技大学","哈尔滨工业大学","北京航空航天大学","北京理工大学","东北大学","东南大学","西安交通大学","西北工业大学","南京航空航天大学","南京理工大学","北京交通大学","北京科技大学","武汉大学","中山大学","四川大学","山东大学","湖南大学","大连理工大学","重庆大学","华南理工大学","华东理工大学","北京化工大学","北京工业大学","合肥工业大学","哈尔滨工程大学","华东交通大学","南京工业大学","浙江工业大学","杭州电子科技大学","重庆邮电大学","沈阳工业大学","辽宁石油化工大学","沈阳航空航天大学","武汉理工大学","湖北工业大学","广东工业大学","广西大学","贵州大学","云南大学","兰州大学","新疆大学","东北师范大学","陕西师范大学","山东师范大学","福建师范大学","华中师范大学","河南大学","山西大学","河北工业大学","燕山大学","中北大学","沈阳理工大学","长春理工大学","哈尔滨工程大学","河海大学","中国矿业大学","江苏科技大学","南通大学","温州大学","华侨大学","暨南大学","厦门大学","深圳北理莫斯科大学","西交利物浦大学","宁波诺丁汉大学"]},
    {"name":"机械类","icon":"⚙️","univs":["清华大学","上海交通大学","浙江大学","华中科技大学","哈尔滨工业大学","北京理工大学","北京航空航天大学","西安交通大学","北京交通大学","北京科技大学","东南大学","东北大学","南京航空航天大学","南京理工大学","西北工业大学","电子科技大学","武汉大学","武汉理工大学","四川大学","重庆大学","山东大学","湖南大学","大连理工大学","吉林大学","合肥工业大学","华东理工大学","北京工业大学","燕山大学","中北大学","沈阳工业大学","沈阳理工大学","辽宁石油化工大学","沈阳航空航天大学","哈尔滨工程大学","华东交通大学","南昌航空大学","南京工业大学","浙江工业大学","杭州电子科技大学","重庆邮电大学","武汉科技大学","湖北工业大学","广东工业大学","广西大学","贵州大学","云南大学","兰州大学","新疆大学","河南科技大学","太原科技大学","内蒙古工业大学","辽宁工程技术大学","辽宁科技大学","沈阳化工大学","长春工业大学","上海工程技术大学","常州大学","苏州大学","江苏大学","扬州大学","南通大学","温州大学","华侨大学","暨南大学","厦门大学","深圳北理莫斯科大学","西交利物浦大学","宁波诺丁汉大学"]},
    {"name":"土木类","icon":"🏗️","univs":["同济大学","东南大学","清华大学","浙江大学","上海交通大学","哈尔滨工业大学","重庆大学","中南大学","湖南大学","大连理工大学","天津大学","西南交通大学","北京交通大学","北京工业大学","北京建筑大学","石家庄铁道大学","华北水利水电大学","太原理工大学","内蒙古工业大学","辽宁工程技术大学","辽宁工业大学","沈阳建筑大学","吉林建筑大学","哈尔滨工程大学","南京工业大学","苏州大学","河海大学","扬州大学","浙江工业大学","宁波大学","华东交通大学","南昌大学","山东大学","山东建筑大学","青岛理工大学","烟台大学","河南理工大学","郑州大学","华中科技大学","武汉理工大学","湖北工业大学","三峡大学","长江大学","中南民族大学","武汉工程大学","桂林理工大学","广西大学","海南大学","贵州大学","昆明理工大学","西南石油大学","四川大学","西南科技大学","成都理工大学","西安建筑科技大学","长安大学","西北工业大学","兰州交通大学","兰州理工大学","新疆大学","青海大学","宁夏大学"]},
    {"name":"临床医学类","icon":"🏥","univs":["北京协和医学院","北京大学","复旦大学","上海交通大学","中山大学","华中科技大学","浙江大学","南京医科大学","四川大学","中南大学","首都医科大学","武汉大学","山东大学","南京大学","中国医科大学","哈尔滨医科大学","广州医科大学","重庆医科大学","天津医科大学","吉林大学","同济大学","东南大学","西安交通大学","苏州大学","郑州大学","厦门大学","兰州大学","广西医科大学","福建医科大学","安徽医科大学","河北医科大学","山西医科大学","温州医科大学","徐州医科大学","南通大学","广东医科大学","深圳大学","南方医科大学","昆明医科大学","贵州医科大学","新疆医科大学","内蒙古医科大学","辽宁中医药大学","长春中医药大学","黑龙江中医药大学"]},
    {"name":"口腔医学类","icon":"🦷","univs":["四川大学","北京大学","上海交通大学","武汉大学","中山大学","南京医科大学","浙江大学","首都医科大学","华中科技大学","中国医科大学","吉林大学","山东大学","重庆医科大学","天津医科大学","广州医科大学","西安交通大学","福建医科大学","郑州大学","广西医科大学","哈尔滨医科大学","遵义医科大学","昆明医科大学","河北医科大学","山西医科大学","温州医科大学","大连医科大学","辽宁何氏医学院","新疆医科大学","内蒙古医科大学","宁夏医科大学","贵州医科大学","海南医学院","皖南医学院","蚌埠医学院","新乡医学院","长治医学院","济宁医学院","滨州医学院","潍坊医学院","泰山医学院"]},
    {"name":"经济学类","icon":"📈","univs":["北京大学","中国人民大学","复旦大学","上海交通大学","浙江大学","南京大学","武汉大学","中山大学","南开大学","中央财经大学","对外经济贸易大学","西南财经大学","中南财经政法大学","上海财经大学","厦门大学","山东大学","四川大学","华中科技大学","北京师范大学","华东师范大学","西安交通大学","东南大学","暨南大学","上海大学","辽宁大学","江西财经大学","东北财经大学","首都经济贸易大学","北京工商大学","天津财经大学","山西财经大学","河北经贸大学","内蒙古大学","辽宁大学","吉林大学","哈尔滨商业大学","华东理工大学","上海对外经贸大学","上海外国语大学","南京审计大学","南京财经大学","浙江工商大学","浙江财经大学","安徽财经大学","福建师范大学","江西师范大学","山东财经大学","河南大学","湖北大学","湖南大学","中南民族大学","湖南师范大学","华南师范大学","广州大学","广西大学","海南大学","重庆工商大学","云南大学","云南财经大学","贵州大学","贵州财经大学","西北大学","兰州大学","兰州财经大学","新疆大学","石河子大学"]},
    {"name":"法学类","icon":"⚖️","univs":["中国政法大学","华东政法大学","西南政法大学","北京大学","中国人民大学","武汉大学","吉林大学","复旦大学","中山大学","厦门大学","南京大学","浙江大学","上海交通大学","四川大学","山东大学","中南财经政法大学","湘潭大学","湖南师范大学","河南大学","辽宁大学","黑龙江大学","云南大学","广西大学","贵州大学","海南大学","西北政法大学","兰州大学","新疆大学","重庆大学","华中科技大学","苏州大学","南京师范大学","上海政法学院","上海大学","广东外语外贸大学","广州大学","深圳大学","华侨大学","福州大学","南昌大学","华东师范大学","陕西师范大学","山东师范大学","福建师范大学","云南师范大学","内蒙古大学","河北大学","河北师范大学","河南师范大学","湖北大学","中南民族大学","扬州大学","江苏师范大学","浙江师范大学","安徽师范大学"]},
    {"name":"金融学类","icon":"💰","univs":["北京大学","清华大学","复旦大学","上海交通大学","中国人民大学","中央财经大学","对外经济贸易大学","上海财经大学","西南财经大学","中南财经政法大学","东北财经大学","厦门大学","浙江大学","南京大学","武汉大学","中山大学","南开大学","山东大学","四川大学","暨南大学","华中科技大学","北京师范大学","西安交通大学","华东师范大学","辽宁大学","江西财经大学","首都经济贸易大学","上海对外经贸大学","南京审计大学","南京财经大学","浙江工商大学","浙江财经大学","安徽财经大学","福建师范大学","广东外语外贸大学","广州大学","深圳大学","重庆工商大学","云南大学","贵州大学","西北大学","兰州大学","新疆大学","石河子大学","内蒙古大学","广西大学","海南大学","河南大学","湖北大学","湖南大学","河南大学"]},
    {"name":"教育学类","icon":"📚","univs":["北京师范大学","华东师范大学","华中师范大学","东北师范大学","陕西师范大学","南京师范大学","华南师范大学","西南大学","山东师范大学","福建师范大学","浙江师范大学","华中师范大学","辽宁师范大学","河南师范大学","云南师范大学","贵州师范大学","四川师范大学","重庆师范大学","西北师范大学","新疆师范大学","内蒙古师范大学","广西师范大学","海南师范大学","上海师范大学","广州大学","宁波大学","广州大学","深圳大学","河南大学","山西大学","河北师范大学","内蒙古师范大学","辽宁师范大学","吉林师范大学","哈尔滨师范大学","江苏师范大学","安徽师范大学","江西师范大学","湖北师范大学","湖南师范大学","贵州师范大学","云南师范大学","陕西师范大学","西北师范大学","青海师范大学","宁夏师范大学","新疆师范大学","海南师范大学"]},
    {"name":"数学类","icon":"🔢","univs":["北京大学","清华大学","复旦大学","浙江大学","上海交通大学","中国科学技术大学","南京大学","山东大学","四川大学","武汉大学","华中科技大学","中山大学","西安交通大学","北京师范大学","华东师范大学","南开大学","吉林大学","东南大学","厦门大学","兰州大学","湖南大学","华南师范大学","苏州大学","华东理工大学","上海大学","北京航空航天大学","哈尔滨工业大学","北京理工大学","西北工业大学","电子科技大学","西安电子科技大学","北京邮电大学","南京航空航天大学","南京理工大学","华中师范大学","东北师范大学","陕西师范大学","南京师范大学","华中师范大学","华南师范大学","西南大学","福建师范大学","江西师范大学","山东师范大学","河南师范大学","湖北大学","云南大学","贵州大学","西北大学","新疆大学","宁夏大学","广西大学","海南大学","内蒙古大学","河北师范大学","辽宁师范大学","吉林师范大学","哈尔滨师范大学","江苏师范大学","安徽师范大学"]},
    {"name":"物理学类","icon":"⚛️","univs":["北京大学","清华大学","中国科学技术大学","复旦大学","南京大学","浙江大学","上海交通大学","华中科技大学","武汉大学","中山大学","西安交通大学","北京师范大学","吉林大学","南开大学","四川大学","山东大学","兰州大学","厦门大学","华南师范大学","华东师范大学","哈尔滨工业大学","北京航空航天大学","北京理工大学","电子科技大学","西安电子科技大学","南京航空航天大学","南京理工大学","西北工业大学","华中师范大学","东北师范大学","陕西师范大学","南京师范大学","华中师范大学","华南师范大学","西南大学","福建师范大学","江西师范大学","山东师范大学","河南师范大学","湖北大学","云南大学","贵州大学","西北大学","新疆大学","宁夏大学","广西大学","海南大学","内蒙古大学","河北师范大学","辽宁师范大学","吉林师范大学","哈尔滨师范大学","江苏师范大学","安徽师范大学","山西大学","中北大学"]},
    {"name":"化学类","icon":"🧪","univs":["北京大学","清华大学","中国科学技术大学","复旦大学","浙江大学","南京大学","上海交通大学","华中科技大学","武汉大学","中山大学","西安交通大学","四川大学","山东大学","南开大学","吉林大学","厦门大学","兰州大学","华东师范大学","北京师范大学","华南师范大学","苏州大学","华东理工大学","北京航空航天大学","哈尔滨工业大学","北京理工大学","电子科技大学","西北工业大学","南京航空航天大学","南京理工大学","华中师范大学","东北师范大学","陕西师范大学","南京师范大学","华中师范大学","华南师范大学","西南大学","福建师范大学","江西师范大学","山东师范大学","河南师范大学","湖北大学","云南大学","贵州大学","西北大学","新疆大学","宁夏大学","广西大学","海南大学","内蒙古大学","河北师范大学","辽宁师范大学","吉林师范大学","哈尔滨师范大学","江苏师范大学","安徽师范大学","山西大学","中北大学"]},
    {"name":"建筑类","icon":"🏛️","univs":["清华大学","同济大学","东南大学","天津大学","华南理工大学","重庆大学","哈尔滨工业大学","浙江大学","华中科技大学","上海交通大学","北京建筑大学","大连理工大学","沈阳建筑大学","南京工业大学","苏州大学","青岛理工大学","山东建筑大学","郑州大学","西安建筑科技大学","长安大学","昆明理工大学","深圳大学","广州大学","四川大学","西南交通大学","湖南大学","中南大学","武汉大学","河北工业大学","华侨大学","厦门大学","福州大学","南昌大学","华东交通大学","广西大学","海南大学","贵州大学","云南大学","兰州大学","西北大学","新疆大学","内蒙古大学","北方工业大学","北京工业大学","北京交通大学","北京林业大学","中国矿业大学（北京）","南京林业大学","扬州大学","浙江工业大学","安徽建筑大学","福建农林大学","华东理工大学","武汉理工大学","湖北工业大学","广东工业大学"]},
    {"name":"新闻传播类","icon":"📰","univs":["中国传媒大学","复旦大学","中国人民大学","武汉大学","南京大学","华中科技大学","四川大学","暨南大学","中山大学","厦门大学","上海交通大学","北京大学","南京师范大学","华东师范大学","上海大学","湖南大学","辽宁大学","重庆大学","深圳大学","广州大学","广东外语外贸大学","广西大学","海南大学","云南大学","贵州大学","郑州大学","河南大学","河北大学","山西大学","内蒙古大学","辽宁师范大学","黑龙江大学","吉林大学","长春理工大学","上海理工大学","上海师范大学","华东理工大学","浙江传媒学院","浙江工业大学","浙江理工大学","宁波大学","安徽大学","福建师范大学","江西师范大学","山东大学","山东师范大学","湖北大学","湖北师范大学","湖南师范大学","西南政法大学","西北大学","陕西师范大学","西北政法大学","兰州大学","西北师范大学","新疆大学","石河子大学"]},
    {"name":"英语/外语类","icon":"🌍","univs":["北京外国语大学","上海外国语大学","广东外语外贸大学","南京大学","北京大学","复旦大学","浙江大学","上海交通大学","武汉大学","中山大学","厦门大学","四川大学","南开大学","山东大学","北京师范大学","华东师范大学","华中师范大学","东北师范大学","陕西师范大学","华南师范大学","西南大学","福建师范大学","浙江师范大学","山东师范大学","上海对外经贸大学","首都师范大学","天津外国语大学","大连外国语大学","四川外国语大学","西安外国语大学","重庆外语外事学院","北京语言大学","北京第二外国语学院","上海对外经贸大学","上海师范大学","华东理工大学","上海大学","浙江工业大学","浙江工商大学","宁波大学","安徽大学","福建师范大学","江西师范大学","河南大学","湖北大学","辽宁师范大学","吉林华侨外国语学院","黑龙江大学","广西大学","海南大学","云南大学","贵州大学","西北大学","新疆大学","内蒙古大学"]},
]

# 论坛帖子
FORUM_POSTS = [
    {"id":1,"user_id":None,"title":"2025年高考志愿填报有什么新变化？","category":"选校咨询","author":"高三家长007","content":"今年是新高考第三年，各省志愿填报规则有哪些调整？平行志愿批次、院校专业组、专业+学校模式有什么区别？希望有经验的学长学姐来解答一下！","views":3420,"likes":89,"tags":["高考志愿","新高考","平行志愿"],"time":"datetime('now','localtime','-2 days')"},
    {"id":2,"user_id":None,"title":"计算机 vs 电子信息，选哪个更好？","category":"专业对比","author":"考生小明","content":"分数能上中等985的计算机，但电子信息也很感兴趣。听说计算机现在卷得厉害，但电子信息好像未来发展也不错。学长学姐们能给点建议吗？主要考虑就业和深造两个方面。","views":2850,"likes":156,"tags":["计算机","电子信息","专业选择"],"time":"datetime('now','localtime','-1 day')"},
    {"id":3,"user_id":None,"title":"985中外合作办学值得读吗？","category":"选校咨询","author":"纠结的家长","content":"孩子分数差一点上985本部，中外合作项目可以上，但每年学费要6-10万。请问这类项目的学历含金量如何？以后申请国外研究生有优势吗？国内就业认可度高不高？","views":4120,"likes":78,"tags":["中外合作","985","留学"],"time":"datetime('now','localtime','-3 days')"},
    {"id":4,"user_id":None,"title":"临床医学八年制和五年制怎么选？","category":"专业对比","author":"医学梦","content":"想学医，但纠结读八年制（本博连读）还是五年制再考研。八年制省时间但学校受限，五年制可以考研冲更好学校。请各位前辈给点意见！","views":1980,"likes":203,"tags":["临床医学","八年制","学医"],"time":"datetime('now','localtime','-5 hours')"},
    {"id":5,"user_id":None,"title":"文科生想转码，可行吗？","category":"就业前景","author":"文科生小李","content":"我是历史专业的，但对编程很感兴趣。想问问文科背景转行计算机现实吗？需要补哪些基础？就业时会被歧视吗？有没有成功的案例可以分享？","views":5680,"likes":312,"tags":["转码","文科生","计算机"],"time":"datetime('now','localtime','-1 day')"},
    {"id":6,"user_id":None,"title":"2025届毕业生就业质量报告汇总","category":"就业前景","author":"数据控","content":"整理了各高校2024届毕业生就业质量报告的数据，包含平均薪资、就业率、主要去向行业。数据来源各校官网公告，有需要的同学可以参考一下！","views":7850,"likes":567,"tags":["就业报告","薪资","数据分析"],"time":"datetime('now','localtime','-12 hours')"},
    {"id":7,"user_id":None,"title":"师范类专业还值得报吗？","category":"选校咨询","author":"老师的孩子","content":"现在出生率下降，教师岗位会不会越来越饱和？免费师范生的优师计划值得签吗？普通师范生和非师范生考教师编有什么区别？","views":3250,"likes":145,"tags":["师范","教师编","优师计划"],"time":"datetime('now','localtime','-2 days')"},
    {"id":8,"user_id":None,"title":"考研vs直接就业，如何抉择？","category":"考研交流","author":"大四学长","content":"现在大三，面临考研还是就业的选择。听说就业市场2025年有所回暖，但学历贬值也越来越明显。文科专业是考研还是直接就业性价比更高？","views":4560,"likes":289,"tags":["考研","就业","人生选择"],"time":"datetime('now','localtime','-4 hours')"},
]

FORUM_COMMENTS = [
    {"id":1,"post_id":1,"author":"过来人2024","text":"平行志愿就是一次投档，院校专业组还要看选科要求，专业+学校最灵活但风险也大，要冲稳保拉开梯度","likes":45,"time":"datetime('now','localtime','-1 day')"},
    {"id":2,"post_id":1,"author":"浙江考生家长","text":"浙江是专业+学校模式，80个志愿要好好研究往年录取位次，冲稳保比例建议3:5:2","likes":38,"time":"datetime('now','localtime','-1 day')"},
    {"id":3,"post_id":2,"author":"CS在读博士","text":"能上985计算机就别犹豫，计算机的壁垒在于算法和系统思维，这两样985平台能给你。电子信息偏硬件，发展也不错但上限没有CS高","likes":89,"time":"datetime('now','localtime','-20 hours')"},
    {"id":4,"post_id":2,"author":"芯片工程师","text":"电子信息现在国家大力扶持，芯片、AI硬件都是风口，而且35岁危机比CS轻。建议根据兴趣来，两个方向都不会差","likes":67,"time":"datetime('now','localtime','-18 hours')"},
    {"id":5,"post_id":3,"author":"中外合作毕业生","text":"读了西浦，个人体验是：资源确实好，但学费要量力而行。申国外研究生有优势，但国内就业部分HR会有顾虑，看具体公司","likes":56,"time":"datetime('now','localtime','-2 days')"},
    {"id":6,"post_id":3,"author":"HR从业者","text":"说实话，国内就业市场对中外合作的认可度在逐年提升，但差距还是存在的。建议优先考虑985本部，哪怕专业差一点","likes":78,"time":"datetime('now','localtime','-2 days')"},
    {"id":7,"post_id":4,"author":"医学研究生","text":"能八年制就八年制，医学考研难度非常大，五年制考研压力极大，而且规培时间都差不多","likes":134,"time":"datetime('now','localtime','-3 days')"},
    {"id":8,"post_id":4,"author":"临床医生10年","text":"八年制的问题是临床经验相对少，很多医院还是看实力。但省时间是真的，可以早点评职称","likes":92,"time":"datetime('now','localtime','-3 days')"},
    {"id":9,"post_id":5,"author":"成功转码者","text":"从历史转CS，现某大厂后端。建议：Python入门，数据结构+算法补齐，做2-3个项目，找实习刷算法题。文科背景反而是差异化优势","likes":178,"time":"datetime('now','localtime','-10 hours')"},
    {"id":10,"post_id":5,"author":"转码群群主","text":"文科生转码最大的障碍不是技术，是思维方式和项目经验。建议早点开始刷LeetCode，系统学习计算机基础","likes":145,"time":"datetime('now','localtime','-8 hours')"},
    {"id":11,"post_id":6,"author":"数据分析狮","text":"计算机类平均年薪25-35万，电子信息20-28万，机械土木15-22万，医学15-25万，文科经管12-20万，仅供参考","likes":289,"time":"datetime('now','localtime','-5 hours')"},
    {"id":12,"post_id":6,"author":"HR小张","text":"补充一下：央国企和公务员薪资比市场低但稳定，大厂波动大但天花板高，要看个人风险偏好","likes":156,"time":"datetime('now','localtime','-4 hours')"},
    {"id":13,"post_id":7,"author":"在职教师","text":"出生率下降确实影响教师需求，但优师计划定向就业有保障。建议考虑物理+化学组合的师范生，目前缺口还比较大","likes":67,"time":"datetime('now','localtime','-1 day')"},
    {"id":14,"post_id":7,"author":"教育部数据","text":"2025年教师资格证报考人数突破1100万，但新增教师岗位只有约80万，确实竞争加剧。但乡村教师缺口依然大","likes":89,"time":"datetime('now','localtime','-1 day')"},
    {"id":15,"post_id":8,"author":"考研名师","text":"文科建议先就业积累经验再决定是否考研。理工科要看具体方向，AI相关必须考研，其他方向可以先工作","likes":112,"time":"datetime('now','localtime','-2 hours')"},
    {"id":16,"post_id":8,"author":"企业HRBP","text":"说实话，研究生学历在职场3年后优势才明显。刚毕业时，实习经历、项目经验比学历更重要","likes":98,"time":"datetime('now','localtime','-1 hour')"},
]
